spring:
  application:
    name: PortfolioProject
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/august
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  logging:
    level:
      org:
        springframework: DEBUG
      hibernate: DEBUG
      spring:
        data:
          jpa: DEBUG
  jwt:
    secret: "m38WLlIBdeRNTbmB2Qy48wVGtH9p9/O2mMZv//ZUsBzg5tQeKydtrTVsDoQ6KjX1JSk88qTz2z3yDoSv5FQ0L+ZCOpO0aEkVoK03L2yBlTknDpuq5XU3vc5DP+EmGhMC"
